verbose: false
instrumentation:
    root: .
    extensions:
        - .js
    default-excludes: true
    excludes: ['lib/browser.js']
reporting:
    print: summary
    reports:
        - json
    dir: ./coverage
    watermarks:
        statements: [90, 95]
        lines: [90, 95]
        functions: [90, 95]
        branches: [90, 95]
