environment:
  matrix:
    - nodejs_version: '5'
    - nodejs_version: '4'
    - nodejs_version: '0.12'
    - nodejs_version: '0.10'
install:
  - ps: Install-Product node :nodejs_version
  - set CI=true
  - npm install
matrix:
  fast_finish: true
build: off
version: '{build}'
shallow_clone: true
clone_depth: 1
test_script:
  - npm run test
