name: 'Tests: node.js < 10'

on: [pull_request, push]

permissions:
  contents: read

jobs:
  tests:
    uses: ljharb/actions/.github/workflows/node.yml@main
    with:
      range: '>= 6 < 10'
      type: minors
      command: npm run ci-test
